apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-micro
  name: auth-micro
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-micro
  template:
    metadata:
      labels:
        app: auth-micro
    spec:
      containers:
      - image: nginx
        name: nginx
